version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - aws s3 cp s3://john-callahan-webpage-resources/applicationProperties.properties ./src/main/resources/applicationProperties.properties
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/*.war ./john-kim_api_p1-1.war
  post_build:
    commands:
      - echo Build completed on `date`
      - unzip john-kim_api_p1-1.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact

